def finish():
    print("\n"*20)
    print("For days, you delicately work on the pulse crystals.")
    print("Any tiny mistake will mean the end of your ship. You'll be stranded here forever...")
    print("\n"*3)
    print("Hit ENTER to continue")
    input("> ")
    print("\n"*20)
    print("Finally the crystals are calibrated. you install them in the ship's engine...")
    print("\n"*3)
    print("Hit ENTER to continue")
    input("> ")
    print("\n"*20)
    print("With trembling fingers, you fire up the engine...")
    print("\n"*3)
    print("Hit ENTER to continue")
    input("> ")
    print("\n"*20)
    print("IT WORKS!")
    print("\n"*3)
    print("Hit ENTER to continue")
    input("> ")
    print("\n"*20)
    print("You point the ship towards the stars.")
    print("With tears in your eyes, you vanish into the night.")
    print("\n"*3)
    print("Hit ENTER to continue")
    input("> ")
    print("\n"*20)
    print("\t\tEND")
    print("\n"*3)
    print("Hit ENTER to quit")
    input("> ")
    exit(0)


finish()
